### ISSUE TITLE
Enum extensions

### ISSUE THREAD

**Issue by ArunPrakashG** [kentcb/humanizer#11]
On the latest version of Dart SDK, it is possible to define extensions on `Enum` types.
Would be neat to see `enum_value.humanized` property on them.
above property converts enum value to string without the type name.

Sample:
```dart
extension EnumExtensions on Enum {
  String get humanized => toString().split('.').last;
}
```

**Comment by kentcb** [comment]
Ah nice, I wasn't aware of that change. I'm glad I held off on adding explicit support for enums now. I think something along the lines of what you're suggesting will make sense, so will take a look when I get time.

Thanks for the suggestion!

**Comment by ArunPrakashG** [comment]
Hey, i submitted a PR regarding this to implement it in the library.
